// Generated by CoffeeScript 1.9.2
(function() {
  var Socket, global;

  Socket = (function() {
    function Socket() {
      console.log('hello');
      this.initWebSocket();
    }

    Socket.prototype.initWebSocket = function() {
      var host, self;
      self = this;
      host = window.document.location.host.replace(/:.*/, '');
      this.ws = new WebSocket('ws://' + host + ':3000');
      return this.ws.onmessage = function(event) {
        if (self.received !== null) {
          return self.onmessage(JSON.parse(JSON.parse(event.data)));
        }
      };
    };

    Socket.prototype.send = function(data) {
      return this.ws.send(JSON.stringify(data));
    };

    Socket.prototype.receive = function(fn) {
      return this.onmessage = fn;
    };

    return Socket;

  })();

  global = this;

  $(function() {
    global.socket = new Socket();
    socket.receive(function(data) {
      return console.log(data);
    });
    return setInterval(function() {
      return socket.send({
        hoge: 2
      });
    }, 1000);
  });

}).call(this);
