// Generated by CoffeeScript 1.9.2
(function() {
  var Socket, global;

  Socket = (function() {
    function Socket() {
      console.log('hello');
      this.initWebSocket();
    }

    Socket.prototype.initWebSocket = function() {
      var host, self;
      self = this;
      host = window.document.location.host.replace(/:.*/, '');
      this.ws = new WebSocket('ws://' + host + ':3000');
      return this.ws.onmessage = function(event) {
        return self.received(JSON.parse(JSON.parse(event.data)));
      };
    };

    Socket.prototype.send = function(data) {
      return this.ws.send(JSON.stringify(data));
    };

    Socket.prototype.received = function(data) {};

    return Socket;

  })();

  global = this;

  $(function() {
    return global.socket = new Socket();
  });

}).call(this);
