// Generated by CoffeeScript 1.9.2
(function() {
  var Socket;

  Socket = (function() {
    function Socket() {
      this.initWebSocket();
    }

    Socket.prototype.initWebSocket = function() {
      var host, self;
      self = this;
      host = window.document.location.host.replace(/:.*/, '');
      this.ws = new WebSocket('ws://' + host + ':3000');
      this.ws.onmessage = function(event) {
        if (self.onmessage != null) {
          return self.onmessage(JSON.parse(event.data));
        }
      };
      this.ws.onopen = function() {
        if (self.onopen != null) {
          return self.onopen();
        }
      };
      this.ws.onerror = function(error) {
        return console.log('WebSocket Error ' + error);
      };
      return this.ws.onclose = function(error) {
        return console.log('WebSocket Error ' + error);
      };
    };

    Socket.prototype.send = function(data) {
      return this.ws.send(JSON.stringify(data));
    };

    return Socket;

  })();

  this.Socket = Socket;

}).call(this);
